name: Github Actions Debug

on:
  push:
    branches: 
      - develop
      - master

jobs:
  build:
    name: Running Units Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - name: Compose up the docker
      run: docker compose -f "docker-compose.yml" up -d --build
    - name: List all container   #remove this step once you're done investigating
      run: docker ps
    - name: Run tests from the built image
      run: docker run survey-form sh -c "npm test"
    - name: Compose down the docker
      run: docker compose -f "docker-compose.yml" down
